version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: financial_manager_server
    restart: always
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    volumes:
      - "./server:/app/server"
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    container_name: financial_manager_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - financial_manager_db:/var/lib/postgresql/data
volumes:
  financial_manager_db:
    driver: local
